name: "Magento 2 installation with DDEV"
author: "Julien Loizelet"
description: " A Github Action for installing Magento 2 with DDEV"

inputs:

  php_version:
    type: string
    required: false
    default: "8.1"
    description: "PHP Version to use"

  magento_edition:
    type: string
    required: false
    default: "magento/project-community-edition"
    description: "The edition of Magento to install"

  magento_version:
    type: string
    required: false
    default: "2.4.6"
    description: "The Magento release version to install"

  magento_repository:
    type: string
    required: false
    default: "https://mirror.mage-os.org/"
    description: "Where to install Magento from"

  composer_auth:
    type: string
    required: false
    description: "Composer authentication credentials"
    default: ""

  varnish_setup:
    type: boolean
    required: false
    description: "Install with ready-to-use Varnish"
    default: false

runs:
  using: "composite"
  steps:

    - name: Install DDEV
      # @see https://ddev.readthedocs.io/en/stable/#installationupgrade-script-linux-and-macos-armarm64-and-amd64-architectures
      shell: bash
      run: |
        curl -fsSL https://apt.fury.io/drud/gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/ddev.gpg > /dev/null
        echo "deb [signed-by=/etc/apt/trusted.gpg.d/ddev.gpg] https://apt.fury.io/drud/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list
        sudo apt-get -q update
        sudo apt-get -q -y install libnss3-tools ddev
        mkcert -install
        ddev config global --instrumentation-opt-in=false --omit-containers=ddev-ssh-agent

    - name: Set M2_VERSION_CODE env
      # used in some directory path and conventional file naming (Example : 2.4.3 => m243; 2.3.7-p4 => m237)
      shell: bash
      run: |
        echo "M2_VERSION_CODE=$(echo m${{ inputs.magento_version }} | grep  -oP "^m([0-9]{1,}\.)([0-9]{1,}\.)([0-9]{1,})(-(p)\.[0-9]{1,})?" | sed 's/\.//g' )" >> $GITHUB_ENV    

    - name: Create empty Magento 2 DDEV project
      shell: bash
      run: ddev config --project-type=magento2 --project-name=${{ env.M2_VERSION_CODE }} --docroot=pub --create-docroot --disable-settings-management

    - name: Install DDEV tools add-on
      shell: bash
      run: ddev get julienloizelet/ddev-tools

    - name: Prepare Elastic search
      shell: bash
      run: ddev get ddev/ddev-elasticsearch

    - name: Set Magento 2 settings
      shell: bash
      id: magento2-settings
      run: echo "url=https://${{ env.M2_VERSION_CODE }}.ddev.site" >> "${GITHUB_OUTPUT}"

    - name: Set COMPOSER_AUTH
      shell: bash
      if: ${{inputs.composer_auth}}
      run: |
        mkdir -p .ddev/homeadditions/.composer
        echo '${{ inputs.composer_auth }}' > .ddev/homeadditions/.composer/auth.json

    - name: Set ELASTIC_INSTALL_STRING env for 2.4
      shell: bash
      if: startsWith(inputs.magento_version, '2.4')
      run: echo "ELASTIC_INSTALL_STRING=--elasticsearch-host=elasticsearch --search-engine=elasticsearch7" >> $GITHUB_ENV

    - name: Set ELASTIC_INSTALL_STRING env for 2.3
      shell: bash
      if: startsWith(inputs.magento_version, '2.3')
      run: echo "ELASTIC_INSTALL_STRING=" >> $GITHUB_ENV

    - name: Handle PHP version
      shell: bash
      run: |
        sed -i -e 's/^php_version:.*/php_version: "${{ inputs.php_version }}"/g' .ddev/config.yaml

    - name: Handle composer version
      shell: bash
      if: contains(fromJson('["2.3.0","2.3.1","2.3.2","2.3.3","2.3.4","2.3.5","2.3.6","2.4.0","2.4.1"]'),matrix.m2-version)
      run: |
        sed -i -e 's/^composer_version:.*/composer_version: "1"/g' .ddev/config.yaml    

    - name: Prepare Varnish
      shell: bash
      if: inputs.varnish_setup == 'true'
      run: |
        ddev get ddev/ddev-varnish
        cp .ddev/okaeli-add-on/magento2/custom_files/varnish-profile.xml varnish-profile.xml
        cp .ddev/okaeli-add-on/magento2/custom_files/default.vcl .ddev/varnish/default.vcl

    - name: Start DDEV for ${{ inputs.magento_version }} with PHP ${{ inputs.php_version }}
      shell: bash
      run: ddev start

    - name: Handle Varnish VCL
      shell: bash
      if: inputs.varnish_setup == 'true'
      run: |
        ddev replace-acl $(ddev find-ip ddev-router)
        ddev reload-vcl  

    - name: Set COMPOSER_VERSION env
      shell: bash
      run: echo "COMPOSER_VERSION=$(ddev exec composer -V | grep -oP "([0-9]{1,}\.)([0-9]{1,}\.)([0-9]{1,})(-(alpha|beta)\.[0-9]{1,})?" )" >> $GITHUB_ENV

    - name: Create Magento ${{ inputs.magento_edition }} ${{ inputs.magento_version }} project
      shell: bash
      # We don't use "ddev composer create" as it restarts all containers
      run: |
        ddev exec composer create --repository="${{ inputs.magento_repository }}" "${{ inputs.magento_edition }}" ${{ env.M2_VERSION_CODE }} ${{ inputs.magento_version }} --no-install
        cp -r ${{ env.M2_VERSION_CODE }}/. ${{ github.workspace }}
        rm -rf ${{ env.M2_VERSION_CODE }}

    - name: Fixup Composer Plugins
      shell: bash
      if: ${{ startsWith(env.COMPOSER_VERSION, '2') }}
      run: |
        ddev composer config --no-interaction allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
        ddev composer config --no-interaction allow-plugins.laminas/laminas-dependency-plugin true
        ddev composer config --no-interaction allow-plugins.magento/* true

    - name: Fixup Composer version audit plugin
      shell: bash
      run: |
          ddev composer config repositories.0 '{"type": "composer", "url":"${{ inputs.magento_repository }}",  "exclude": ["magento/composer-dependency-version-audit-plugin"]}'

    - name: Fixup Monolog
      # @see https://github.com/magento/magento2/pull/35596
      shell: bash
      if: contains(fromJson('["2.4.4"]'),inputs.magento_version)
      run: ddev composer require monolog/monolog:"<2.7.0" --no-update

    - name: Install composer 1 plugin for parallel downloads
      shell: bash
      run: ddev composer global require hirak/prestissimo
      if: ${{ startsWith(env.COMPOSER_VERSION, '1') }}

    - name: Install Magento
      shell: bash
      run: ddev exec composer install

    - name: Setup Magento ${{ inputs.magento_edition }} ${{ inputs.magento_version }}
      shell: bash
      run: |
        ddev magento setup:install \
                         --base-url=${{ steps.magento2-settings.outputs.url }} \
                         --db-host=db \
                         --db-name=db \
                         --db-user=db \
                         --db-password=db \
                         --backend-frontname=admin \
                         --admin-firstname=admin \
                         --admin-lastname=admin \
                         --admin-email=admin@admin.com \
                         --admin-user=admin \
                         --admin-password=admin123 \
                         --language=en_US \
                         --currency=USD \
                         --timezone=America/Chicago \
                         --use-rewrites=1 \
                         ${{ env.ELASTIC_INSTALL_STRING }}

outputs:
  m2_url:
    description: "The freshly installed Magento 2 instance url."
    value: ${{ steps.magento2-settings.outputs.url }}

branding:
  icon: "code"
  color: "green"
