name: Documentation links

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
jobs:
  markdown-test-links:
    name: Markdown test links
    runs-on: ubuntu-latest
    steps:

      - name: Clone sources
        uses: actions/checkout@v3
        with:
          path: sources

      - name: Launch localhost server
        run: |
          sudo npm install --global http-server
          http-server ./sources &

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Check links in Markdown files
        run: |
          gem install awesome_bot
          cd sources
          awesome_bot README.md --skip-save-results --allow-dupe --base-url http://localhost:8080/ --white-list repo.magento.com,ddev.site
